<a href="https://colab.research.google.com/github/KRISHNA07MISHRA/Numpy_learning/blob/main/practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr1 = np.array([1,2,3])

In [ ]:
arr1

array([1, 2, 3])

In [ ]:
arr1.size

3

In [ ]:
arr1.itemsize

8

In [ ]:
arr2 = np.ones

In [ ]:
arr2

<function numpy.ones(shape, dtype=None, order='C', *, like=None)>

In [ ]:
arr3 = np.ones((2,3))

In [ ]:
arr3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
arr3.itemsize

8

In [ ]:
arr5 = np.zeros((2,2))
arr5

array([[0., 0.],
       [0., 0.]])

In [ ]:
arr5.size

4

In [ ]:
arr5.itemsize

8

In [ ]:
arr5.dtype

dtype('float64')

In [ ]:
lista = range(100)
arr1 = np.arange(100)

In [ ]:
import sys

In [ ]:
print(sys.getsizeof(87)*len(lista))

2800


In [ ]:
print(arr1.itemsize*arr1.size)

800


In [ ]:
import time

In [ ]:
x = range(10000000)
y = range(10000000,20000000)

In [ ]:
start_time = time.time()
c = [(x,y)for x,y in zip(x,y)]
print(time.time()-start_time)

3.289600133895874


In [ ]:
a = np.arange(10000000)
b = np.arange(10000000,20000000)
start_time = time.time()
c = a+b
print(time.time()-start_time)

0.04168343544006348


In [ ]:
arr12 = np.arange(24).reshape(6,4)

In [ ]:
arr12

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
import numpy as np

In [ ]:
arr13 = np.arange(24).reshape(6,4)

In [ ]:
arr13

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [ ]:
arr1 = np.array([1,2,3,4,5])

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1[3]

4

In [ ]:
arr1[2:4]

array([3, 4])

In [ ]:
arr1[-1]

5

In [ ]:
arr13[2]

array([ 8,  9, 10, 11])

In [ ]:
arr13[:,2]



array([ 2,  6, 10, 14, 18, 22])

In [ ]:
arr13[2,1]

9

In [ ]:
arr13[-2]

array([16, 17, 18, 19])

In [ ]:
arr13[2:1:3,3:1:3]

array([], shape=(0, 0), dtype=int64)

In [ ]:
arr13[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [ ]:
arr13[4,2:3]

array([18])

In [ ]:
arr13[4,2]

18

In [ ]:
arr13[4:,2:]

array([[18, 19],
       [22, 23]])

In [ ]:
 for i in np.nditer(arr13):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23


In [ ]:
print("krishna")

krishna


In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1 += 6

In [ ]:
arr1


array([ 7,  8,  9, 10, 11])

In [ ]:
arr1 -= 6

In [ ]:
arr1

array([1, 2, 3, 4, 5])

In [ ]:
arr1.put(4,6)
arr1

array([1, 2, 3, 4, 6])

In [ ]:
arr1.min

<function ndarray.min>

In [ ]:
arr2 = np.array([7,8,9,10,12])

In [ ]:
arr1*arr2

array([ 7, 16, 27, 40, 72])

In [ ]:
arr1>3

array([False, False, False,  True,  True])

In [ ]:
arr3 = np.arange(6).reshape(2,3)
arr4 = np.arange(6,12).reshape(3,2)

In [ ]:
arr3.dot(arr4)

array([[ 28,  31],
       [100, 112]])

In [ ]:
arr4

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [ ]:
arr4.max

<function ndarray.max>

In [ ]:
arr4.max()

11

In [ ]:
arr4.min(axis = 0)

array([6, 7])

In [ ]:
arr4.min(axis = 1)

array([ 6,  8, 10])

In [ ]:
arr4.sum()

51

In [ ]:
arr4.mean()

8.5

In [ ]:
arr4.sum(axis = 0)

array([24, 27])

In [ ]:
np.sin(arr4)

NameError: name 'np' is not defined

In [ ]:
np.median(arr4)

8.5

In [ ]:
import numpy as np

In [1]:
arr1 = np.array([1,2,3])

NameError: name 'np' is not defined

In [2]:
import numpy as np

In [3]:
arr1 = np.array([1,2,4,5])
arr1

array([1, 2, 4, 5])